name: Build and deploy to production
on: 
  push:
    branches: 
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Zola
      run: |
        wget -O zola.deb ${{ secrets.ZOLA_DEBIAN }}
        sudo dpkg -i zola.deb
    - name: Check Zola links
      run: |
        zola check
    - name: Build Zola site
      run: |
        zola build
    - name: rsync files
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: public/
        remote_path: /home/fribyte/fribyte.no/public
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.KEY }}
        remote_port: ${{ secrets.PORT }}
